Marketplace
IsitaB/KinKin pull request #27
Opened 2022-04-08 02:58 UTC by christinang3030

2022-04-08 06:42 UTC, charlotte-zhuang requested changes
Just need to change `class=` to `className=` in `Marketplace.jsx`

2022-04-08 06:43 UTC, JoshuaLawson8 approved these changes
looks good, need to fill in send R/M

2022-04-13 19:30 UTC, thibui0908 approved these changes

2022-04-14 03:48 UTC, christinang3030 commented
In Progress
--> Will wait for the backend to complete before integrating into frontend.

2022-04-15 03:00 UTC, closed without merging