setup testing. added testing files
IsitaB/KinKin pull request #41
Opened 2022-04-21 21:33 UTC by euniceyoh

run with `npm test`

2022-04-21 22:44 UTC, isabellapiz approved these changes

2022-04-22 01:20 UTC, charlotte-zhuang requested changes
I'm seeing an error documented [here](https://github.com/facebook/create-react-app/issues/11792). The solution that worked for me was to install another module: `npm i -D --exact jest-watch-typeahead@0.6.5`

Also need to add `coverage/` to `.gitignore`

2022-04-22 01:20 UTC, charlotte-zhuang commented on package.json
> +    "jest": "^26.6.3",
```suggestion
    "jest-watch-typeahead": "^0.6.5",
    "jest": "^26.6.3",
```

2022-04-22 01:58 UTC, charlotte-zhuang approved these changes

2022-04-22 02:40 UTC, christinang3030 approved these changes
Test suites look good.

2022-04-22 02:42 UTC, IsitaB approved these changes

2022-04-22 04:12 UTC, merged